### ISSUE TITLE
Fix: Seitennummerierung für PDF Anzeigeprogramm

### ISSUE THREAD

**Issue by moritzrfs** [tsipiluka/bachelor#5]
Falsche Anzeige/Nummerierung wegen Dopplung mit Nummer der Titelseite:
![image](https://github.com/tsipiluka/bachelor/assets/73069661/9935ab1a-3582-4b59-b80a-eb13b22f007e)

**Comment by moritzrfs** [comment]
Für Titlepage Nummerierung auf Alphabetisch setzen, sodass als Seitennummer im Programm A angezeigt wird:

```
\pagenumbering{Alph}
\setcounter{page}{1} 
```

Nach Titlepage dann wieder regulär
```
\pagenumbering{roman}
```

![image](https://github.com/tsipiluka/bachelor/assets/73069661/93257f54-7d95-4255-bded-dea2b901c0bf)

**Comment by tsipiluka** [comment]
Hab in commit [c0a2d](https://github.com/tsipiluka/bachelor/commit/c0a2d939fb988a975fb1dbeb5e40023b0156dc02) geändert. Stimmt jetzt?

**Comment by moritzrfs** [comment]
> Hab in commit [c0a2d](https://github.com/tsipiluka/bachelor/commit/c0a2d939fb988a975fb1dbeb5e40023b0156dc02) geändert. Stimmt jetzt?

Ja stimmt jetzt
